#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TimeGear.Resource", IsApplication=true)]

namespace TimeGear
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int clock = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int entire_progress = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int preference_value = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int stage_name_text = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int stage_progress = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int start_button = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int timer_activity_layout = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int toolbar_settings = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int toolbar_title_image = 2131165191;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ClockText = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EntireProgressBar = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int NumberEditTextPreference = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Preferences = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int StageNameText = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int StageProgress = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int StartButton = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int TimerActivity = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Toolbar = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050011
			public const int Cancel = 2131034129;
			
			// aapt resource value: 0x7f05000b
			public const int EntireProgress = 2131034123;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int Interface = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int Interval = 2131034119;
			
			// aapt resource value: 0x7f050015
			public const int Lack = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int LongBreak = 2131034132;
			
			// aapt resource value: 0x7f050006
			public const int LongBreakTime = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int Notifications = 2131034121;
			
			// aapt resource value: 0x7f050002
			public const int Pomodoro = 2131034114;
			
			// aapt resource value: 0x7f050013
			public const int ShortBreak = 2131034131;
			
			// aapt resource value: 0x7f050005
			public const int ShortBreakTime = 2131034117;
			
			// aapt resource value: 0x7f05000c
			public const int StageProgress = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int StartButton = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int StartLongBreak = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int StartShortBreak = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int StartWork = 2131034126;
			
			// aapt resource value: 0x7f050003
			public const int Time = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int Toolbar = 2131034122;
			
			// aapt resource value: 0x7f050012
			public const int Work = 2131034130;
			
			// aapt resource value: 0x7f050004
			public const int WorkTime = 2131034116;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060004
			public const int ButtonStyle = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int ClockStyle = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int MyTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int ProgressBarStyle = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int TextViewStyle = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int Preferences = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
